<?php

namespace app\controllers;

use amnah\yii2\user\models\User;
use app\models\Lecturer;
use app\models\Student;
use Yii;
use yii\helpers\Url;
use yii\web\Controller;

/**
 * Created by PhpStorm.
 * User: faridyusof727
 * Date: 03/08/2017
 * Time: 11:47 AM
 */
class ManageController extends Controller
{
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(['/user/login']);
            Yii::$app->response->send();
        }

        if (!Yii::$app->user->can('admin')) {
            $this->redirect(Url::home());
            Yii::$app->response->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {

    }

    public function actionAddStudent()
    {
        return $this->render('add-student');
    }

    public function actionDoAddStudent()
    {
        $data = Yii::$app->request->post();

        $user = new User();
        $user->attributes = $data['User'];
        $user->status = 1;
        $user->role_id = 2;
        $user->newPassword = $data['User']['password'];
        $user->newPasswordConfirm = $data['User']['password'];

        if ($user->save()) {
            $student = new Student();
            $student->attributes = $data['Student'];
            $student->id = $user->id;

            if ($student->save()) {
                Yii::$app->session->setFlash('success', 'Record saved successfully.');
                $this->redirect(['/manage/add-student']);
                Yii::$app->response->send();
            } else {
                // bila x berjaya
                $user->delete();
                Yii::$app->session->setFlash('error', 'Record cannot save.');
                $this->redirect(['/manage/add-student']);
                Yii::$app->response->send();
            }

        } else {
            Yii::$app->session->setFlash('error', 'Record cannot save.');
            $this->redirect(['/manage/add-student']);
            Yii::$app->response->send();
        }

    }

    public function actionAddLecturer() {
        $user = new User();
        $lecturer = new Lecturer();

        if (Yii::$app->request->isPost) {

            $user->load(Yii::$app->request->post());
            $user->status = 1;
            $user->role_id = 2;
            $user->newPasswordConfirm = $user->newPassword;

            $lecturer->load(Yii::$app->request->post());
            if($user->save()) {
                $lecturer->id = $user->id;
                if ($lecturer->save()) {
                    Yii::$app->session->setFlash('success', 'Record saved successfully.');
                    $this->redirect(['/manage/add-lecturer']);
                    Yii::$app->response->send();
                    return true;
                }
            }

        }

        return $this->render('add-lecturer', [
            'user' => $user,
            'lecturer' => $lecturer
        ]);
    }
}