<?php
/**
 * Created by PhpStorm.
 * User: faridyusof727
 * Date: 04/08/2017
 * Time: 12:41 PM
 */

namespace app\models;

class GlobalActiveRecord extends \yii\db\ActiveRecord {


    public function beforeSave($insert)
    {

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}